//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.28 at 07:39:20 PM EEST 
//


package myschema;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="movie" type="{http://spring.io/guides/gs-producing-web-service}movie"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "movie"
})
@XmlRootElement(name = "getMovieResponse")
public class GetMovieResponse {

    @XmlElement(required = true)
    protected Movie movie;

    /**
     * Gets the value of the movie property.
     *
     * @return possible object is
     * {@link Movie }
     */
    public Movie getMovie() {
        return movie;
    }

    /**
     * Sets the value of the movie property.
     *
     * @param value allowed object is
     *              {@link Movie }
     */
    public void setMovie(Movie value) {
        this.movie = value;
    }

}
