//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.28 at 07:39:20 PM EEST 
//


package myschema;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the io.spring.guides.gs_producing_web_service package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChangeActorRequest }
     */
    public ChangeActorRequest createChangeActorRequest() {
        return new ChangeActorRequest();
    }

    /**
     * Create an instance of {@link Actor }
     */
    public Actor createActor() {
        return new Actor();
    }

    /**
     * Create an instance of {@link ChangeActorResponse }
     */
    public ChangeActorResponse createChangeActorResponse() {
        return new ChangeActorResponse();
    }

    /**
     * Create an instance of {@link DeleteActorRequest }
     */
    public DeleteActorRequest createDeleteActorRequest() {
        return new DeleteActorRequest();
    }

    /**
     * Create an instance of {@link DeleteActorResponse }
     */
    public DeleteActorResponse createDeleteActorResponse() {
        return new DeleteActorResponse();
    }

    /**
     * Create an instance of {@link AddDirectorRequest }
     */
    public AddDirectorRequest createAddDirectorRequest() {
        return new AddDirectorRequest();
    }

    /**
     * Create an instance of {@link Director }
     */
    public Director createDirector() {
        return new Director();
    }

    /**
     * Create an instance of {@link AddDirectorResponse }
     */
    public AddDirectorResponse createAddDirectorResponse() {
        return new AddDirectorResponse();
    }

    /**
     * Create an instance of {@link GetMovieActorsRequest }
     */
    public GetMovieActorsRequest createGetMovieActorsRequest() {
        return new GetMovieActorsRequest();
    }

    /**
     * Create an instance of {@link GetMovieActorsResponse }
     */
    public GetMovieActorsResponse createGetMovieActorsResponse() {
        return new GetMovieActorsResponse();
    }

    /**
     * Create an instance of {@link GetAllMoviesRequest }
     */
    public GetAllMoviesRequest createGetAllMoviesRequest() {
        return new GetAllMoviesRequest();
    }

    /**
     * Create an instance of {@link GetAllMoviesResponse }
     */
    public GetAllMoviesResponse createGetAllMoviesResponse() {
        return new GetAllMoviesResponse();
    }

    /**
     * Create an instance of {@link Movie }
     */
    public Movie createMovie() {
        return new Movie();
    }

    /**
     * Create an instance of {@link GetMoviesByGenreRequest }
     */
    public GetMoviesByGenreRequest createGetMoviesByGenreRequest() {
        return new GetMoviesByGenreRequest();
    }

    /**
     * Create an instance of {@link GetMoviesByGenreResponse }
     */
    public GetMoviesByGenreResponse createGetMoviesByGenreResponse() {
        return new GetMoviesByGenreResponse();
    }

    /**
     * Create an instance of {@link GetMovieRequest }
     */
    public GetMovieRequest createGetMovieRequest() {
        return new GetMovieRequest();
    }

    /**
     * Create an instance of {@link GetMovieResponse }
     */
    public GetMovieResponse createGetMovieResponse() {
        return new GetMovieResponse();
    }

    /**
     * Create an instance of {@link Genre }
     */
    public Genre createGenre() {
        return new Genre();
    }

    /**
     * Create an instance of {@link Writer }
     */
    public Writer createWriter() {
        return new Writer();
    }

    /**
     * Create an instance of {@link MovieReview }
     */
    public MovieReview createMovieReview() {
        return new MovieReview();
    }

    /**
     * Create an instance of {@link User }
     */
    public User createUser() {
        return new User();
    }

}
